// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LodBasen.Models;

[Table("Admin")]
public partial class Admin
{
    [Key]
    [Column("Admin_ID")]
    public int AdminId { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Navn { get; set; }

    public int Antal { get; set; }

    public int Udleveret { get; set; }

    [InverseProperty("Admin")]
    public virtual ICollection<Sælger> Sælgere { get; set; } = new List<Sælger>();
}