// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LodBasen.Models;

[Table("Leder")]
public partial class Leder
{
    [Key]
    [Column("Leder_ID")]
    public int LederId { get; set; }

    [Required(ErrorMessage = "Leder navn er påkrævet")]
    [StringLength(30)]
    [Unicode(false)]
    public string Navn { get; set; }

    public int Antal { get; set; }

    public int Udleveret { get; set; }

    [Column("Gruppe_ID")]
    public int GruppeId { get; set; }

    [ForeignKey("GruppeId")]
    [InverseProperty("Ledere")]
    public virtual Gruppe Gruppe { get; set; }

    [InverseProperty("Leder")]
    public virtual ICollection<Modtager> Modtagere { get; set; } = new List<Modtager>();

    [InverseProperty("Leder")]
    public virtual ICollection<Sælger> Sælgere { get; set; } = new List<Sælger>();
}