// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LodBasen.Models;

[Table("Lodseddel")]
public partial class Lodseddel
{
    [Key]
    [Column("Lodseddel_ID")]
    public int LodseddelId { get; set; }

    public int Antal { get; set; }

    public int Solgt { get; set; }

    [InverseProperty("Lodseddel")]
    public virtual ICollection<Lodsalg> Lodsalgssamling { get; set; } = new List<Lodsalg>();
}