// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LodBasen.Models;

[Table("Lodsalg")]
public partial class Lodsalg
{
    [Key]
    [Column("Lodsalgs_ID")]
    public int LodsalgsId { get; set; }

    [Column("Sælger_ID")]
    public int SælgerId { get; set; }

    [Column("Modtager_ID")]
    public int ModtagerId { get; set; }

    [Column("Lodseddel_ID")]
    public int LodseddelId { get; set; }

    [ForeignKey("LodseddelId")]
    [InverseProperty("Lodsalgssamling")]
    public virtual Lodseddel Lodseddel { get; set; }

    [ForeignKey("ModtagerId")]
    [InverseProperty("Lodsalgssamling")]
    public virtual Modtager Modtager { get; set; }

    [ForeignKey("SælgerId")]
    [InverseProperty("Lodsalgssamling")]
    public virtual Sælger Sælger { get; set; }
}