// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LodBasen.Models;

[Table("Modtager")]
public partial class Modtager
{
    [Key]
    [Column("Modtager_ID")]
    public int ModtagerId { get; set; }

    [Column("Leder_ID")]
    public int? LederId { get; set; }

    [Column("Barn_ID")]
    public int? BarnId { get; set; }

    [ForeignKey("BarnId")]
    [InverseProperty("Modtagers")]
    public virtual Barn Barn { get; set; }

    [ForeignKey("LederId")]
    [InverseProperty("Modtagers")]
    public virtual Leder Leder { get; set; }

    [InverseProperty("Modtager")]
    public virtual ICollection<Lodsalg> Lodsalgs { get; set; } = new List<Lodsalg>();
}