// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LodBasen.Models;

[Table("Sælger")]
public partial class Sælger
{
    [Key]
    [Column("Sælger_ID")]
    public int SælgerId { get; set; }

    [Column("Leder_ID")]
    public int? LederId { get; set; }

    [Column("Admin_ID")]
    public int? AdminId { get; set; }

    [ForeignKey("AdminId")]
    [InverseProperty("Sælgere")]
    public virtual Admin Admin { get; set; }

    [ForeignKey("LederId")]
    [InverseProperty("Sælgere")]
    public virtual Leder Leder { get; set; }

    [InverseProperty("Sælger")]
    public virtual ICollection<Lodsalg> Lodsalgssamling { get; set; } = new List<Lodsalg>();
}